<?php

/**
 * @file
 * Contains \Drupal\example\Controller\ExampleController.
namespace Drupal\example\Controller;
 */

namespace Drupal\example;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Controller\ControllerBase;

/**
 * Displays content for our menu links.
 */
class ExampleController extends ControllerBase{

  public function __construct() {
    //    parent::__construct();
    $this->destination = \Drupal::request()->query->get('destination');
    $this->transport = \Drupal::request()->query->get('transport');
  }
  
  public function getTitle() {
    $reply = t('So you want to visit @destination?', array('@destination' => $this->destination));
    e_debug(__FUNCTION__,func_get_args(),$reply);
    return $reply;
  }
  
  public function getAccess() {
    static $case;
    $reply = (bool)($this->destination == 'Saturn');
    e_debug(__FUNCTION__,func_get_args(),$reply);
    return ($reply 
	    ? AccessResult::allowed() 
	    : AccessResult::forbidden());   // AccessResult::neutral();
    return $reply;
  }
  
  public function getContent() {
    e_debug(__FUNCTION__,func_get_args());
    $markup = '<p>' . t('Let\'s go to @destination via our luxury @transport!', array('@destination' => $this->destination, '@transport' => $this->transport)) . '</p>';
    return array(
		 '#type' => 'markup',
		 '#markup' => $markup,
		 );
  }
}

function e_debug($function,$func_get_args,$reply=''){
  $msg = sprintf('%s(%s): <em>%s</em>',$function,var_export($func_get_args,True),var_export($reply,True),'status');
  drupal_set_message($msg,'warning',True);
}
