<?php
$image_src = myPear_images . '../../'.EA_MODULE.'/includes/nordita_board_57.jpg';
?>
<table width=509>
<tr>
<td>
<img src='<?php print $image_src; ?>' alt='Photo of NORDITA Board of directors'>
</td>
</tr>
<tr>
<td style='text-align:center:'>
<h3>NORDITA Board of directors, 1957-58</h3>
  	    
<em>(standing): </em>
<b>Klein</b>&nbsp;Oskar&nbsp;Benjamin,
<b>Bohr</b>&nbsp;Aage,
<b>Lindhard</b>&nbsp;Jens,
<b>Hyllerås</b>&nbsp;Egil&nbsp;Andersen,
<b>Bøggild</b>&nbsp;Jørgen&nbsp;Kruse,
<b>Nielsen</b>&nbsp;Leo,
<b>Møller</b>&nbsp;Christian,
<b>Rozental</b>&nbsp;Stefan,
<b>Jauho</b>&nbsp;Pekka

<br/>
<em>(sitting):</em> 
<b>Holtsmark</b>&nbsp;Johan&nbsp;Peter,
<b>Waller</b>&nbsp;Ivar,
<b>Funke</b>&nbsp;Gösta,
<b>Rosseland</b>&nbsp;Svein,
<b>Wergeland</b>&nbsp;Harald&nbsp;Nicolai,
<b>Bohr</b>&nbsp;Niels

</td>
</tr>
</table>
