<?php
/**
 * @file
 *
 */

function wiw_init(){
  static $dejaVu = 0;
  if (!$dejaVu++) {
    myPear_init();
    if (function_exists('ea_init')) ea_init();
    require_once drupal_get_path('module','wiw') . "/config.inc";
    locateAndInclude('APImenu_wiw');
  }
}

/*
 * Chanell the auto-learn translations
 */
function wiw_t($text){
  return t(bText::_(array('key' =>"WIW_MENU_$text",
			   'item'=>$text)));
}

function _wiw_access_callback($tab){
  wiw_init();
  return WIW::_MENU()->access($tab);
}

/**
 * Implementation of hook_menu()
 */
function wiw_menu(){
  wiw_init();
  return WIW::_MENU()->build_menuTree('_wiw_output');
}

function wiw_footer(){
  wiw_init();
}


/*
 * Display output
 */
function _wiw_output($arg=Null,$arg2=Null){
  wiw_init();
  $file_cache = new b_cache_file();
  if ($file_cache->notYetReady())    WIW::_MENU()->process($arg,$arg2);
  return $file_cache->get();
}

function wiw_page_alter(&$page) {
  wiw_init();
  $page['page_bottom']['devel']=array('#type' => 'markup',
				      '#markup' => wiw_footer());
}

if (class_exists('Drupal',False)){
  
  function wiw_user_login($account) {
    wiw_init();
    // Reset static cache of default variables in template_preprocess() to reflect the new user.
    drupal_static_reset('template_preprocess');
    // Authenticate to myPear
    locateAndInclude('bAuth');
    bAuth::drupal_hook_user($account);
  }

  function wiw_user_logout($account) {
    // Reset static cache of default variables in template_preprocess() to reflect the new user.
    drupal_static_reset('template_preprocess');
  }

}else{
  /*
   * Implements hook_user
   */
  function wiw_user($type, $array, $account, $category){
    wiw_init();
    locateAndInclude('bAuth');
    bAuth::drupal_hook_user($account);
  }

  function wiw_user_login($edit, $account) {
    wiw_init();
    locateAndInclude('bAuth');
    bAuth::drupal_hook_user($account);
  }
}

if (is_file($f=drupal_get_path('module','myPear').'/includes/drupal8_compat.inc')) require_once $f;
