#!/bin/sh

case "$1" in
  start)
        /usr/local/mysql/bin/safe_mysqld &
	;;
  stop)
        /usr/local/mysql/bin/mysqladmin shutdown -pmysql
	;;
  *)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0

