<?php

/**
 * @file
 * Page Load Progress allows you to set a screen lock showing a spinner when the
 * user clicks on an element that triggers a time consuming task.
 */

/**
 * Implements hook_menu().
 */
function page_load_progress_menu() {
  $item = array('title' => 'Page Load Progress',
		'description' => 'Manage the behavior of Page Load Progress.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('page_load_progress_settings'),
		'access arguments' => array('administer Page Load Progress settings'),
		'file' => 'page_load_progress.admin.inc',
		'type' => MENU_NORMAL_ITEM,
		);
  if (defined('VERSION')) $items = array('admin/config/user-interface/page_load_progress' => $item); // drupal 7 / 8
  else                    $items = array('admin/settings/page_load_progress' => $item);              // drupal 6
  return $items;
}

/**
 * Implements hook_permission().
 */
function page_load_progress_permission() {
  return array('administer Page Load Progress settings' => array('title' => t('Administer Page Load Progress settings')));
}

/**
 * Implements hook_init().
 */
function page_load_progress_init() {

  $path = drupal_get_path('module','page_load_progress');
  drupal_add_css("$path/page_load_progress.css");
  if (defined('VERSION')) drupal_add_js ("$path/page_load_progress.js",'file');
  else                    drupal_add_js ("$path/page_load_progress.js",'core');
  
  drupal_add_js(array('page_load_progress' => array('delay'   => variable_get('page_load_progress_time', 10),
						    'elements'=> variable_get('page_load_progress_elements', '.page_load_progress,.form-submit'))),
		'setting');
}
