<?php
/**
 * @file
 *
 */

/**
 * Implementation of hook_init()
 */
function vm_init(){
  static $dejaVu = 0;
  if (!$dejaVu++){
    if (function_exists('myPear_init')){
      myPear_init();
    }elseif(class_exists('Drupal',False)){
      drupal_set_message('??? myPear module is not yet loaded, trying to load','error');
      //      require_once drupal_get_path('module','myPear').'/config.inc';
    }else{
      drupal_set_message('??? Drupal is not yet loaded','error');
    }
    require_once drupal_get_path('module','vm') . '/config.inc';
    drupal_add_css('./'.drupal_get_path('module','vm').'/css/vm.css');
  }
}

function _vm_access_callback($tab){
  vm_init();
  locateAndInclude('APImenu_vm');
  return VM::_MENU()->access($tab);
}

/**
 * Implementation of hook_menu()
 */
function vm_menu(){
  vm_init();
  $menu = VM::_MENU()->build_menuTree('_vm_output');
  return $menu;
}

/*
 * Display output
 */
function _vm_output($arg=Null,$arg2=Null){
  vm_init();
  $file_cache = new b_cache_file();
  if ($file_cache->notYetReady())    VM::_MENU()->process($arg,$arg2);
  return $file_cache->get();
}

/*
 * Drupal 6
 */
function vm_footer(){
  vm_init();
  ob_start();
  if (function_exists('bJS')) bJS()->flush(); 
  $output = ob_get_contents();
  ob_end_clean();
  return $output;
}

/**
 * Implements hook_page_alter(), drupal7 replace-mt of hook_footer
 */
function vm_page_alter(&$page) {
  vm_init();
  $page['page_bottom']['devel']=array('#type' => 'markup',
				      '#markup' => vm_footer());
}

if (class_exists('Drupal',False)){
  
  function vm_user_login($account) {
    vm_init();
    // Reset static cache of default variables in template_preprocess() to reflect the new user.
    drupal_static_reset('template_preprocess');
    // Authenticate to myPear
    locateAndInclude('bAuth');
    bAuth::drupal_hook_user($account);
  }
  
  function vm_user_logout($account) {
    // Reset static cache of default variables in template_preprocess() to reflect the new user.
    drupal_static_reset('template_preprocess');
  }
  
}else{
  /*
   * Implements hook_user
   */
  function vm_user($type, $array, $account, $category){
    vm_init();
    locateAndInclude('bAuth');
    bAuth::drupal_hook_user($account);
  }

  function vm_user_login($edit, $account) {
    vm_init();
    locateAndInclude('bAuth');
    bAuth::drupal_hook_user($account);
  }
}

if (is_file($f=drupal_get_path('module','myPear').'/includes/drupal8_compat.inc')) require_once $f;

