<?php
locateAndInclude('pdf_form');

function SU_9009(){
  return array(
	       't01' => array('t'=>'Landskod',          'c' => ''),
	       't02' => array('t'=>'Valutakod',         'c' => ''),
	       't03' => array('t'=>'Betalningsvillkor', 'c' => ''),
	       't04' => array('t'=>'undefined_4',       'c' => ''),
	       't05' => array('t'=>'Namn',              'c' => ''),
	       't06' => array('t'=>'Befintligt',        'c' => ''),
	       't07' => array('t'=>'Ny',                'c' => ''),
	       't08' => array('t'=>'Andring',           'c' => ''),
	       't09' => array('t'=>'Kontoinnehavare',   'c' => 'pdf_Lf'),
	       't10' => array('t'=>'Adress',            'c' => ''),
	       't11' => array('t'=>'Ort',               'c' => ''),
	       't12' => array('t'=>'Banknamn',          'c' => ''),
	       't13' => array('t'=>'Bankadress',        'c' => ''),
	       't14' => array('t'=>'Bankort',           'c' => ''),
	       't15' => array('t'=>'Vara',              'c' => ''),
	       't16' => array('t'=>'SwiftadressBIC',    'c' => ''),
	       't17' => array('t'=>'Kontonumm',         'c' => ''),
	       't18' => array('t'=>'Bankbranch',        'c' => ''),
	       't19' => array('t'=>'VATnummer',         'c' => ''),
	       't20' => array('t'=>'Ja',                'c' => ''),
	       't21' => array('t'=>'Institution',       'c' => ''),
	       't22' => array('t'=>'Telefon',           'c' => ''),
	       't23' => array('t'=>'DatumU',            'c' => ''),
	       't24' => array('t'=>'Datum1',            'c' => ''),
	       );
}

