<?php

/**
 * @file
 * Contains \Drupal\theme_switcher
 */
 
namespace Drupal\theme_switcher;
 
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Theme\ThemeNegotiatorInterface;
 
class ThemeSwitcher implements ThemeNegotiatorInterface {

  public  static $themes = array('albanova.se' => 'an',
				 'nordita.org' => 'nordita');
  private static $theme = '';
  
  public function applies(RouteMatchInterface $route_match) {

    foreach(self::$themes as $url=>$theme){
      if (
	  ($_REQUEST['org'] == $theme) ||
	  ($_REQUEST['flavor'] == $theme) ||
	  (stripos($_SERVER['HTTP_HOST'],$url) !== False)
	  )  self::$theme = $theme;
    }
    return !empty(self::$theme);
  }
  
  /**
   * {@inheritdoc}
   */
  public function determineActiveTheme(RouteMatchInterface $route_match) {
    return self::$theme;
  }
}
