CREATE TABLE IF NOT EXISTS `jam_positions` (
  `pos_id` int(11) NOT NULL AUTO_INCREMENT,
  `pos_logo` varchar(132) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_status` int(11) NOT NULL DEFAULT '0',
  `pos_name` varchar(128) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_nickname` varchar(24) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_refnumber` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pos_type` varchar(12) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_email` varchar(132) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_bcc` varchar(128) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pos_desc` text COLLATE utf8_unicode_ci,
  `pos_url` varchar(132) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pos_n_referees` tinyint(4) NOT NULL DEFAULT '-1',
  `pos_req_phd` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pos_req_phd_year` int(11) NOT NULL DEFAULT '0',
  `pos_req_ms` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pos_req_nation` varchar(32) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_sc_maybe_referee` varchar(32) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_deadline` int(11) DEFAULT NULL,
  `pos_startup` int(11) DEFAULT NULL,
  `pos_ap_noreply` varchar(8) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_av_noreply` varchar(8) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `pos_namesc1` varchar(230) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Faculty members',
  `pos_namesc2` varchar(230) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Research Committee members',
  `pos_orgid` int(32) NOT NULL DEFAULT '0',
  `pos_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pos_req_cv` varchar(128) CHARACTER SET utf8  NOT NULL,
  `pos_req_mt` varchar(128) CHARACTER SET utf8  NOT NULL,
  `pos_req_pl` varchar(128) CHARACTER SET utf8  NOT NULL,
  `pos_req_rp` varchar(128) CHARACTER SET utf8  NOT NULL,
  `pos_req_er` varchar(128) CHARACTER SET utf8  NOT NULL,
  PRIMARY KEY (`pos_id`)
) AUTO_INCREMENT=1;
